apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: dotnetbuild
spec:
  mountTrustedCA: true
  failedBuildsHistoryLimit: 1
  successfulBuildsHistoryLimit: 2
  output:
    to:
      kind: ImageStreamTag
      name: dotnetbuild:1.0.0
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    type: Git
    git:
      uri: https://github.com/lindasavecore/test.git
      ref: main
    contextDir: dotnet/src
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: dotnet:6.0-ubi8
        namespace: openshift
      incremental: true
      env:
      - name: VERBOSITY_OPTION
        value: d
      - name: DOTNET_DEFAULT_CMD
        value: wut
      - name: DOTNET_FRAMEWORK
        value: net6.0
      - name: DOTNET_PACK
        value: "false"
      - name: DOTNET_APP_PATH
        value: out
      - name: DOTNET_STARTUP_PROJECT
        value: app.csproj
      - name: DOTNET_CONFIGURATION
        value: Release
      - name: DOTNET_INCREMENTAL
        value: "true"
  triggers: []
